"""Music section: MuseScore-exported notation, MusicXML for interchange."""
def build_music(out, base, page):
    def save(route,title,body):
        target=out/route
        target.mkdir(parents=True,exist_ok=True)
        (target/'index.html').write_text(page(title,body))
    def card(href,title,description):
        return f'<article class="card"><div class="card-body"><p class="eyebrow">PARTITURAS · EXPERIMENTO</p><h2>{title}</h2><p>{description}</p><a class="button" href="{base}/{href}/">Explorar ↗</a></div></article>'
    save('musica','Música',f'<section class="article-layout"><p class="eyebrow">UM ESPAÇO PARA ESTUDAR E TOCAR</p><h1>Música<span class="dot">.</span></h1><p class="lead">Partituras e experiências musicais. Uma nova seção do Manual do Maker, começando pela leitura de partituras.</p><div class="music-catalog">{card("musica/msa","MSA","Coleção experimental de partituras. Abra o primeiro estudo para testar a leitura.")}</div></section>')
    save('musica/msa','MSA',f'<section class="article-layout"><a class="text-link" href="{base}/musica/">← Música</a><p class="eyebrow">MÚSICA / MSA</p><h1>MSA</h1><p class="lead">Primeira partitura disponível para experimentar o novo espaço.</p><div class="music-catalog">{card("musica/msa/107-msa-bb","107 - MSA - Bb","Clarinete em Si♭ · P. Bona · 1 página")}</div></section>')
    assets=f'{base}/assets/music/107-msa-bb'
    body=f'''<section class="article-layout score-section"><nav class="breadcrumbs" aria-label="Caminho da partitura"><a href="{base}/musica/">Música</a><span>/</span><a href="{base}/musica/msa/">MSA</a></nav><p class="eyebrow">PARTITURA EXPERIMENTAL</p><h1>107 - MSA - Bb</h1><p class="lead">Clarinete em Si♭ · P. Bona</p><div class="score-toolbar"><label for="score-zoom">Tamanho da partitura</label><select id="score-zoom"><option value="100">Ajustar à tela</option><option value="150">150%</option><option value="200">200%</option></select><a class="button" href="{assets}/score.musicxml" download="107 - MSA - Bb.musicxml">Baixar MusicXML ↓</a><a class="text-link" href="{assets}/score-1.svg" target="_blank" rel="noopener">Abrir página em tamanho original ↗</a></div><p class="score-note">Áudio de clarinete exportado pelo MuseScore, com cursor sincronizado às notas e pausas. Use o controle de velocidade para estudar sem alterar a afinação.</p><div class="score-player"><audio id="score-audio" controls preload="none" data-timing="{assets}/timing.json"><source src="{assets}/score.ogg" type="audio/ogg"><source src="{assets}/score.mp3" type="audio/mpeg">Seu navegador não suporta áudio. <a href="{assets}/score.mp3">Baixar áudio</a></audio><div class="player-options"><button id="restart-score" type="button">Voltar ao início</button><label>Velocidade <select id="playback-speed"><option value="0.5">0,5×</option><option value="0.75">0,75×</option><option value="1" selected>Normal</option><option value="1.25">1,25×</option><option value="1.5">1,5×</option></select></label><label><input id="follow-cursor" type="checkbox" checked> Acompanhar cursor</label><span id="current-measure">Compasso 1 de 13</span></div><p id="playback-status" role="status">Carregando cursor…</p></div><div class="score-viewport" tabindex="0" role="region" aria-label="Partitura com rolagem horizontal"><div id="score-sheet"><div id="score-cursor" hidden aria-hidden="true"></div><img id="score-image" src="{assets}/score-1.svg" alt="Partitura 107 - MSA - Bb, de P. Bona, para clarinete em Si bemol. Página 1 de 1." width="1020" height="1320"></div></div><p class="score-note">Página 1 de 1 · Exportada do arquivo 107 - MSA - Bb.mscz. O MusicXML mantém os dados musicais para intercâmbio com editores compatíveis.</p></section><script type="module" src="{base}/assets/music.js"></script>'''
    save('musica/msa/107-msa-bb','107 - MSA - Bb',body)
