"""Music section: MuseScore-exported notation, MusicXML for interchange."""
def build_music(out, base, page):
    def save(route,title,body):
        target=out/route
        target.mkdir(parents=True,exist_ok=True)
        (target/'index.html').write_text(page(title,body))
    def card(href,title,description):
        return f'<article class="card"><div class="card-body"><p class="eyebrow">PARTITURAS · EXPERIMENTO</p><h2>{title}</h2><p>{description}</p><a class="button" href="{base}/{href}/">Explorar ↗</a></div></article>'
    save('musica','Música',f'<section class="article-layout"><p class="eyebrow">UM ESPAÇO PARA ESTUDAR E TOCAR</p><h1>Música<span class="dot">.</span></h1><p class="lead">Partituras e experiências musicais. Uma nova seção do Manual do Maker, começando pela leitura de partituras.</p><div class="music-catalog">{card("musica/msa","MSA","Coleção experimental de partituras. Abra o primeiro estudo para testar a leitura.")}</div></section>')
    save('musica/msa','MSA',f'<section class="article-layout"><a class="text-link" href="{base}/musica/">← Música</a><p class="eyebrow">MÚSICA / MSA</p><h1>MSA</h1><p class="lead">Primeira partitura disponível para experimentar o novo espaço.</p><div class="music-catalog">{card("musica/msa/107-msa-bb","107 - MSA - Bb","Clarinete em Si♭ · P. Bona · 1 página")}</div></section>')
    assets=f'{base}/assets/music/107-msa-bb'
    body=f'''<section class="article-layout score-section"><nav class="breadcrumbs" aria-label="Caminho da partitura"><a href="{base}/musica/">Música</a><span>/</span><a href="{base}/musica/msa/">MSA</a></nav><p class="eyebrow">PARTITURA EXPERIMENTAL</p><h1>107 - MSA - Bb</h1><p class="lead">Clarinete em Si♭ · P. Bona</p><div class="score-toolbar"><label for="score-zoom">Tamanho da partitura</label><select id="score-zoom"><option value="100">Ajustar à tela</option><option value="150">150%</option><option value="200">200%</option></select><a class="button" href="{assets}/score.musicxml" download="107 - MSA - Bb.musicxml">Baixar MusicXML ↓</a><a class="text-link" href="{assets}/score-1.svg" target="_blank" rel="noopener">Abrir página em tamanho original ↗</a></div><p class="score-note">Leitura preservando a diagramação do MuseScore. No celular, amplie e deslize a partitura para os lados. A reprodução de áudio será uma próxima etapa.</p><div class="score-viewport" tabindex="0" role="region" aria-label="Partitura com rolagem horizontal"><img id="score-image" src="{assets}/score-1.svg" alt="Partitura 107 - MSA - Bb, de P. Bona, para clarinete em Si bemol. Página 1 de 1." width="1020" height="1320"></div><p class="score-note">Página 1 de 1 · Exportada do arquivo 107 - MSA - Bb.mscz. O MusicXML mantém os dados musicais para intercâmbio com editores compatíveis.</p></section><script src="{base}/assets/music.js" defer></script>'''
    save('musica/msa/107-msa-bb','107 - MSA - Bb',body)
