"""Static HTML for the original Manual do Maker browser tools."""
def build_tools(out, base, page):
    items=[('matrix','Matriz LED UNO R4','Desenhe nos 96 LEDs e copie o frame em C++.'),('rgb-converter','Conversor RGB','Converta cores RGB24 para RGB565 de 16 bits.'),('resistor','Calculadora de resistores','Leia as quatro faixas e confira resistência e tolerância.')]
    def save(slug,title,content):
        path=out/slug;path.mkdir(exist_ok=True)
        body=f'<section class="article-layout tools"><a class="text-link" href="{base}/toolbox/">← Ferramentas</a><p class="eyebrow">NA SUA BANCADA · DIRETO NO NAVEGADOR</p><h1>{title}</h1>{content}<noscript>Ative o JavaScript para usar esta ferramenta.</noscript></section><script type="module" src="{base}/assets/tools.js"></script>'
        (path/'index.html').write_text(page(title,body))
    cards=''.join(f'<article class="card"><div class="card-body"><p class="eyebrow">FERRAMENTA / 0{i+1}</p><h2>{title}</h2><p>{desc}</p><a class="button" href="{base}/{slug}/">Abrir ferramenta ↗</a></div></article>' for i,(slug,title,desc) in enumerate(items))
    save('toolbox','Ferramentas para criar.',f'<p class="lead">Suas ferramentas do Manual do Maker, em uma nova bancada. Todos os cálculos acontecem no seu navegador.</p><div class="cards">{cards}</div>')
    save('matrix','Matriz LED UNO R4 WiFi', '''<p class="lead">Clique ou toque nos LEDs para desenhar. Use Tab e espaço para editar pelo teclado.</p><div class="tool-grid"><div class="tool-panel"><div id="led-grid" aria-label="Matriz de 8 linhas por 12 colunas"></div><div class="tool-actions"><button id="clear-matrix">Limpar</button><button id="invert-matrix">Inverter</button></div><p id="led-count" aria-live="polite"></p></div><div class="tool-panel"><label for="matrix-code">Código gerado · matriz e três palavras de 32 bits</label><textarea id="matrix-code" rows="17" readonly spellcheck="false"></textarea><button data-copy="matrix-code">Copiar código</button></div></div><details><summary>Como usar no Arduino</summary><p>Use <code>matrix.renderBitmap(bitmap, 8, 12)</code> para a matriz bidimensional ou <code>matrix.loadFrame(frame)</code> para as três palavras de 32 bits, após inicializar a biblioteca Arduino_LED_Matrix.</p><a href="https://docs.arduino.cc/tutorials/uno-r4-wifi/led-matrix/">Documentação Arduino ↗</a></details>''')
    save('rgb-converter','RGB24 → RGB565', '''<p class="lead">Escolha uma cor, digite R, G e B ou informe um hexadecimal. O resultado é atualizado automaticamente.</p><div class="tool-grid"><div class="tool-panel"><div class="color-fields"><label>Vermelho<input id="red" type="number" min="0" max="255" step="1" value="255"></label><label>Verde<input id="green" type="number" min="0" max="255" step="1" value="128"></label><label>Azul<input id="blue" type="number" min="0" max="255" step="1" value="0"></label></div><label for="hex-color">Hexadecimal RGB24</label><input id="hex-color" value="#FF8000" maxlength="7" spellcheck="false"><label for="color-picker">Escolher cor</label><input type="color" id="color-picker" value="#ff8000"><p id="rgb-error" role="status"></p></div><div class="tool-panel"><div id="color-swatch" aria-label="Prévia da cor"></div><label for="rgb-result">RGB565 hexadecimal</label><input id="rgb-result" readonly><p id="rgb-decimal"></p><button data-copy="rgb-result">Copiar RGB565</button></div></div><details><summary>Sobre a conversão</summary><p>São 5 bits para vermelho, 6 para verde e 5 para azul. A redução descarta os bits menos significativos: <code>((R &gt;&gt; 3) &lt;&lt; 11) | ((G &gt;&gt; 2) &lt;&lt; 5) | (B &gt;&gt; 3)</code>. Alguns displays exigem a troca da ordem dos bytes; este resultado está na ordem RGB565 padrão.</p></details>''')
    names=['Preto','Marrom','Vermelho','Laranja','Amarelo','Verde','Azul','Violeta','Cinza','Branco']
    colors=['#151515','#80452b','#d33432','#f18d35','#f0d64b','#448657','#3974b5','#8355a8','#858585','#ffffff','#c2a344','#bcbcbc']
    def select(id,label,options,default):
        return f'<label>{label}<select id="{id}">'+''.join(f'<option value="{value}" data-color="{colors[color]}" {"selected" if value==default else ""}>{name}</option>' for value,name,color in options)+'</select></label>'
    fields=select('digit-one','1ª faixa',[(i,names[i],i) for i in range(1,10)],4)+select('digit-two','2ª faixa',[(i,n,i) for i,n in enumerate(names)],7)+select('multiplier','Multiplicador',[(i,n+' · ×10^'+str(i),i) for i,n in enumerate(names)]+[(-1,'Dourado · ×0,1',10),(-2,'Prata · ×0,01',11)],2)+select('tolerance','Tolerância',[(1,'Marrom · ±1%',1),(2,'Vermelho · ±2%',2),(.5,'Verde · ±0,5%',5),(.25,'Azul · ±0,25%',6),(.1,'Violeta · ±0,1%',7),(.05,'Cinza · ±0,05%',8),(5,'Dourado · ±5%',10),(10,'Prata · ±10%',11)],5)
    save('resistor','Resistores de quatro faixas',f'''<p class="lead">Selecione as cores da esquerda para a direita, com a faixa de tolerância à direita.</p><div class="tool-panel"><div class="resistor-preview" aria-hidden="true"><div class="resistor-body"><i></i><i></i><i></i><i></i></div></div><div class="resistor-fields">{fields}</div><output id="resistor-result" aria-live="polite"></output><p id="resistor-range"></p><p id="resistor-series"></p></div><details><summary>O que significa E12?</summary><p>E12 é uma série de valores preferenciais. Um valor fora dessa série não é necessariamente inválido: pode pertencer a outra série ou ser especial.</p><a href="https://www.digikey.com/en/resources/conversion-calculators/conversion-calculator-resistor-color-code">Referência de cores e multiplicadores ↗</a></details>''')
